import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-mro-consignment-vmi-invoice-audit",
  "engine": "recovery",
  "title": "MRO Consignment & VMI Invoice Audit",
  "shortTitle": "MRO Consignment and VMI Invoice Audit",
  "tagline": "Quantify, recover, and prevent financial leakage through mro consignment & vmi invoice audit",
  "industry": "MRO Inventory Spend Recovery",
  "uiPort": 4613,
  "apiPort": 5613,
  "accent": "#0369a1",
  "currency": "USD",
  "primaryOutcome": "MRO Consignment & VMI Invoice Audit converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect VMI and consignment agreements, storerooms, bins, items, beginning balances, receipts, issues, cycle counts, prices, obsolete stock, emergency charges, invoices, and credits in one accountable recovery workflow.",
  "calculation": {
    "actualKey": "billedAmount",
    "expectedKey": "supportedAmount",
    "actualLabel": "Supplier Billed Amount",
    "expectedLabel": "Consumption-Supported Amount",
    "varianceLabel": "Potential recovery or avoided cost",
    "direction": "actual-minus-expected",
    "finding": "MRO Consignment & VMI Invoice Audit evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective governing agreement and applicable rules",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare and submit the recovery or correction package",
      "Track counterparty response and reconcile realized outcome"
    ]
  }
},[
feature("vmi-contract-library","MCV01","VMI contract library","Execute vmi contract library using VMI and consignment agreements, storerooms, bins, items, beginning balances, receipts, issues, cycle counts, prices, obsolete stock, emergency charges, invoices, and credits.","Produce a governed vmi contract library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Storeroom","text","Supplier / Storeroom · Standard Case"],["caseReference","VMI contract library Reference","text","MCV01-2026-001"],["billedAmount","Supplier Billed Amount","currency",827000],["supportedAmount","Consumption-Supported Amount","currency",711220],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["VMI contract library case","Storeroom bin registry case","Item substitute master case","Beginning inventory reconciliation case","Receipt issue ingestion case"]}),
feature("storeroom-bin-registry","MCV02","Storeroom bin registry","Execute storeroom bin registry using VMI and consignment agreements, storerooms, bins, items, beginning balances, receipts, issues, cycle counts, prices, obsolete stock, emergency charges, invoices, and credits.","Produce a governed storeroom bin registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Storeroom","text","Supplier / Storeroom · Standard Case"],["caseReference","Storeroom bin registry Reference","text","MCV02-2026-001"],["billedAmount","Supplier Billed Amount","currency",827000],["supportedAmount","Consumption-Supported Amount","currency",711220],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["VMI contract library case","Storeroom bin registry case","Item substitute master case","Beginning inventory reconciliation case","Receipt issue ingestion case"]}),
feature("item-substitute-master","MCV03","Item substitute master","Execute item substitute master using VMI and consignment agreements, storerooms, bins, items, beginning balances, receipts, issues, cycle counts, prices, obsolete stock, emergency charges, invoices, and credits.","Produce a governed item substitute master decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Storeroom","text","Supplier / Storeroom · Standard Case"],["caseReference","Item substitute master Reference","text","MCV03-2026-001"],["billedAmount","Supplier Billed Amount","currency",827000],["supportedAmount","Consumption-Supported Amount","currency",711220],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["VMI contract library case","Storeroom bin registry case","Item substitute master case","Beginning inventory reconciliation case","Receipt issue ingestion case"]}),
feature("beginning-inventory-reconciliation","MCV04","Beginning inventory reconciliation","Execute beginning inventory reconciliation using VMI and consignment agreements, storerooms, bins, items, beginning balances, receipts, issues, cycle counts, prices, obsolete stock, emergency charges, invoices, and credits.","Produce a governed beginning inventory reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Storeroom","text","Supplier / Storeroom · Standard Case"],["caseReference","Beginning inventory reconciliation Reference","text","MCV04-2026-001"],["billedAmount","Supplier Billed Amount","currency",827000],["supportedAmount","Consumption-Supported Amount","currency",711220],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["VMI contract library case","Storeroom bin registry case","Item substitute master case","Beginning inventory reconciliation case","Receipt issue ingestion case"]}),
feature("receipt-issue-ingestion","MCV05","Receipt issue ingestion","Execute receipt issue ingestion using VMI and consignment agreements, storerooms, bins, items, beginning balances, receipts, issues, cycle counts, prices, obsolete stock, emergency charges, invoices, and credits.","Produce a governed receipt issue ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Storeroom","text","Supplier / Storeroom · Standard Case"],["caseReference","Receipt issue ingestion Reference","text","MCV05-2026-001"],["billedAmount","Supplier Billed Amount","currency",827000],["supportedAmount","Consumption-Supported Amount","currency",711220],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["VMI contract library case","Storeroom bin registry case","Item substitute master case","Beginning inventory reconciliation case","Receipt issue ingestion case"]}),
feature("cycle-count-variance","MCV06","Cycle count variance","Execute cycle count variance using VMI and consignment agreements, storerooms, bins, items, beginning balances, receipts, issues, cycle counts, prices, obsolete stock, emergency charges, invoices, and credits.","Produce a governed cycle count variance decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Storeroom","text","Supplier / Storeroom · Standard Case"],["caseReference","Cycle count variance Reference","text","MCV06-2026-001"],["billedAmount","Supplier Billed Amount","currency",827000],["supportedAmount","Consumption-Supported Amount","currency",711220],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["VMI contract library case","Storeroom bin registry case","Item substitute master case","Beginning inventory reconciliation case","Receipt issue ingestion case"]}),
feature("consumption-billing-calculation","MCV07","Consumption billing calculation","Execute consumption billing calculation using VMI and consignment agreements, storerooms, bins, items, beginning balances, receipts, issues, cycle counts, prices, obsolete stock, emergency charges, invoices, and credits.","Produce a governed consumption billing calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Storeroom","text","Supplier / Storeroom · Standard Case"],["caseReference","Consumption billing calculation Reference","text","MCV07-2026-001"],["billedAmount","Supplier Billed Amount","currency",827000],["supportedAmount","Consumption-Supported Amount","currency",711220],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["VMI contract library case","Storeroom bin registry case","Item substitute master case","Beginning inventory reconciliation case","Receipt issue ingestion case"]}),
feature("price-discount-validation","MCV08","Price discount validation","Execute price discount validation using VMI and consignment agreements, storerooms, bins, items, beginning balances, receipts, issues, cycle counts, prices, obsolete stock, emergency charges, invoices, and credits.","Produce a governed price discount validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Storeroom","text","Supplier / Storeroom · Standard Case"],["caseReference","Price discount validation Reference","text","MCV08-2026-001"],["billedAmount","Supplier Billed Amount","currency",827000],["supportedAmount","Consumption-Supported Amount","currency",711220],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["VMI contract library case","Storeroom bin registry case","Item substitute master case","Beginning inventory reconciliation case","Receipt issue ingestion case"]}),
feature("obsolete-inventory-responsibility","MCV09","Obsolete inventory responsibility","Execute obsolete inventory responsibility using VMI and consignment agreements, storerooms, bins, items, beginning balances, receipts, issues, cycle counts, prices, obsolete stock, emergency charges, invoices, and credits.","Produce a governed obsolete inventory responsibility decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Storeroom","text","Supplier / Storeroom · Standard Case"],["caseReference","Obsolete inventory responsibility Reference","text","MCV09-2026-001"],["billedAmount","Supplier Billed Amount","currency",827000],["supportedAmount","Consumption-Supported Amount","currency",711220],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["VMI contract library case","Storeroom bin registry case","Item substitute master case","Beginning inventory reconciliation case","Receipt issue ingestion case"]}),
feature("emergency-premium-audit","MCV10","Emergency premium audit","Execute emergency premium audit using VMI and consignment agreements, storerooms, bins, items, beginning balances, receipts, issues, cycle counts, prices, obsolete stock, emergency charges, invoices, and credits.","Produce a governed emergency premium audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Storeroom","text","Supplier / Storeroom · Standard Case"],["caseReference","Emergency premium audit Reference","text","MCV10-2026-001"],["billedAmount","Supplier Billed Amount","currency",827000],["supportedAmount","Consumption-Supported Amount","currency",711220],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["VMI contract library case","Storeroom bin registry case","Item substitute master case","Beginning inventory reconciliation case","Receipt issue ingestion case"]}),
feature("restocking-fee-control","MCV11","Restocking fee control","Execute restocking fee control using VMI and consignment agreements, storerooms, bins, items, beginning balances, receipts, issues, cycle counts, prices, obsolete stock, emergency charges, invoices, and credits.","Produce a governed restocking fee control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Storeroom","text","Supplier / Storeroom · Standard Case"],["caseReference","Restocking fee control Reference","text","MCV11-2026-001"],["billedAmount","Supplier Billed Amount","currency",827000],["supportedAmount","Consumption-Supported Amount","currency",711220],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["VMI contract library case","Storeroom bin registry case","Item substitute master case","Beginning inventory reconciliation case","Receipt issue ingestion case"]}),
feature("invoice-matching","MCV12","Invoice matching","Execute invoice matching using VMI and consignment agreements, storerooms, bins, items, beginning balances, receipts, issues, cycle counts, prices, obsolete stock, emergency charges, invoices, and credits.","Produce a governed invoice matching decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Storeroom","text","Supplier / Storeroom · Standard Case"],["caseReference","Invoice matching Reference","text","MCV12-2026-001"],["billedAmount","Supplier Billed Amount","currency",827000],["supportedAmount","Consumption-Supported Amount","currency",711220],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["VMI contract library case","Storeroom bin registry case","Item substitute master case","Beginning inventory reconciliation case","Receipt issue ingestion case"]}),
feature("supplier-discrepancy-workflow","MCV13","Supplier discrepancy workflow","Execute supplier discrepancy workflow using VMI and consignment agreements, storerooms, bins, items, beginning balances, receipts, issues, cycle counts, prices, obsolete stock, emergency charges, invoices, and credits.","Produce a governed supplier discrepancy workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Storeroom","text","Supplier / Storeroom · Standard Case"],["caseReference","Supplier discrepancy workflow Reference","text","MCV13-2026-001"],["billedAmount","Supplier Billed Amount","currency",827000],["supportedAmount","Consumption-Supported Amount","currency",711220],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["VMI contract library case","Storeroom bin registry case","Item substitute master case","Beginning inventory reconciliation case","Receipt issue ingestion case"]}),
feature("credit-reconciliation","MCV14","Credit reconciliation","Execute credit reconciliation using VMI and consignment agreements, storerooms, bins, items, beginning balances, receipts, issues, cycle counts, prices, obsolete stock, emergency charges, invoices, and credits.","Produce a governed credit reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Storeroom","text","Supplier / Storeroom · Standard Case"],["caseReference","Credit reconciliation Reference","text","MCV14-2026-001"],["billedAmount","Supplier Billed Amount","currency",827000],["supportedAmount","Consumption-Supported Amount","currency",711220],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["VMI contract library case","Storeroom bin registry case","Item substitute master case","Beginning inventory reconciliation case","Receipt issue ingestion case"]}),
feature("plant-item-analytics","MCV15","Plant item analytics","Execute plant item analytics using VMI and consignment agreements, storerooms, bins, items, beginning balances, receipts, issues, cycle counts, prices, obsolete stock, emergency charges, invoices, and credits.","Produce a governed plant item analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Storeroom","text","Supplier / Storeroom · Standard Case"],["caseReference","Plant item analytics Reference","text","MCV15-2026-001"],["billedAmount","Supplier Billed Amount","currency",827000],["supportedAmount","Consumption-Supported Amount","currency",711220],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["VMI contract library case","Storeroom bin registry case","Item substitute master case","Beginning inventory reconciliation case","Receipt issue ingestion case"]})
]);
